### PR TITLE
Execute tests in GitHub Actions. Closes #16

### LINKED ISSUE #16: Fix CI failures & enable tests
ATM CI runs static code analysis tools and they fail. All issues must be fixed.

Additionally we must enable the test suite & reporting to tcms.tenant.kiwitcms.org and remove Travis CI configuration.

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
@RMadjev see stack trace in CI log. I only see paths/functions from vendored libraries and I can't figure out which part of our own code is calling those to point me to the failure.

File: src/Api/JsonRpc/Repository/TestExecutionRepository.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ public function create(TestExecution $model): TestExecution
             'run_id' => $modelData['run']
         ]));
 
-        $result = $response->getRpcResult();
+        $result = $response->getRpcResult()[0];
```
Comment (atodorov) [inline src/Api/JsonRpc/Repository/TestExecutionRepository.php:67]: Note: since v11 this method returns a list and if the test case has parameters (we call them properties) then multiple executions need to be created. Can you open an issue for this to be fixed later? The approach in other plugins is that they iterate over the results.

File: src/PHPUnit/PHPUnitTestListener.php [hunk 2]
```diff
@@ -19,6 +19,16 @@ class PHPUnitTestListener implements TestListener
...
+        set_error_handler(function ($errno, $errstr, $errfile, $errline) {
+            echo $errstr;
+        });
+
+        set_exception_handler(function ($exception) {
+            echo $exception->getMessage();
+            echo "\n";
+            echo $exception->getTraceAsString();
+        });
+
```
Comment (atodorov) [inline src/PHPUnit/PHPUnitTestListener.php]: Can you explain what this is doing, I don't understand? 

Is this related to the fix or a general improvement?

Comment (RMadjev) [reply src/PHPUnit/PHPUnitTestListener.php]: No, its for debugging purposes, I will remove it. Just needed more details about the exception and where it occur.

File: src/Api/JsonRpc/Repository/TestExecutionRepository.php (hunk 1 above)
Comment (atodorov) [reply src/Api/JsonRpc/Repository/TestExecutionRepository.php:67]: https://github.com/kiwitcms/phpunit-plugin/issues/28

**Comment by atodorov** [comment]
@RMadjev I was about to merge this PR but then I noticed the following in the logs:

`Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON`

There seems to be some problem but we don't exit with a non-zero to indicate that.
1) Exit status should be set accordingly, expecting this CI to fail once that's the case
2) Whatever error is there should be fixed.

**Comment by atodorov** [comment]
Reported into https://tcms.kiwitcms.org/runs/1215/
